### ISSUE TITLE
What does this project do?

### ISSUE THREAD

**Issue by GavinNovate** [Kotlin/kotlinx.team.infra#11]
I found it in this project(https://github.com/Kotlin/kotlinx.collections.immutable), But I don't know what it does.

I'm guessing this project is used to upload components to the Maven repository, but don't know how to use it.

I also have a kotlin multiplatform project component that needs to be uploaded to a maven repository.

Maybe a README document is needed to explain what it does.

**Comment by qwwdfsad** [comment]
This project is undocumented deliberately -- it's an internal tool that simplifies build setup for specific kinds of libraries for our particular TeamCity agent layout.

We would like to avoid moving this into the masses and making other people rely on it
